-- 外部数据 - 睡眠记录表
CREATE TABLE IF NOT EXISTS `external_sleep_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `user_id` INT NOT NULL COMMENT '用户ID',
  `data_source` VARCHAR(50) NOT NULL DEFAULT 'xiaomi_sport' COMMENT '数据来源：xiaomi_sport=小米运动健康',
  `source_id` VARCHAR(100) COMMENT '来源数据ID',
  `data_hash` VARCHAR(64) NOT NULL COMMENT '数据哈希值（用于防重）',
  `sleep_date` DATE NOT NULL COMMENT '睡眠日期',
  `start_time` TIMESTAMP NOT NULL COMMENT '入睡时间',
  `end_time` TIMESTAMP NOT NULL COMMENT '起床时间',
  `total_duration` INT COMMENT '总睡眠时长（分钟）',
  `deep_sleep` INT COMMENT '深睡时长（分钟）',
  `light_sleep` INT COMMENT '浅睡时长（分钟）',
  `rem_sleep` INT COMMENT 'REM睡眠时长（分钟）',
  `awake_time` INT COMMENT '清醒时长（分钟）',
  `sleep_score` INT COMMENT '睡眠评分',
  `raw_data` JSON COMMENT '原始数据（JSON格式）',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_data_hash` (`data_hash`) COMMENT '数据哈希唯一',
  INDEX `idx_user_date` (`user_id`, `sleep_date`),
  INDEX `idx_user_source` (`user_id`, `data_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部数据-睡眠记录';

-- 外部数据 - 锻炼记录表
CREATE TABLE IF NOT EXISTS `external_exercise_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `user_id` INT NOT NULL COMMENT '用户ID',
  `data_source` VARCHAR(50) NOT NULL DEFAULT 'xiaomi_sport' COMMENT '数据来源：xiaomi_sport=小米运动健康',
  `source_id` VARCHAR(100) COMMENT '来源数据ID',
  `data_hash` VARCHAR(64) NOT NULL COMMENT '数据哈希值（用于防重）',
  `exercise_date` DATE NOT NULL COMMENT '锻炼日期',
  `start_time` TIMESTAMP NOT NULL COMMENT '开始时间',
  `end_time` TIMESTAMP NOT NULL COMMENT '结束时间',
  `exercise_type` VARCHAR(50) COMMENT '运动类型',
  `duration` INT COMMENT '运动时长（分钟）',
  `distance` DECIMAL(10, 2) COMMENT '运动距离（米）',
  `calories` INT COMMENT '消耗卡路里',
  `steps` INT COMMENT '步数',
  `avg_heart_rate` INT COMMENT '平均心率',
  `max_heart_rate` INT COMMENT '最大心率',
  `raw_data` JSON COMMENT '原始数据（JSON格式）',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_data_hash` (`data_hash`) COMMENT '数据哈希唯一',
  INDEX `idx_user_date` (`user_id`, `exercise_date`),
  INDEX `idx_user_source` (`user_id`, `data_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部数据-锻炼记录';

-- 外部数据 - 体重记录表
CREATE TABLE IF NOT EXISTS `external_weight_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `user_id` INT NOT NULL COMMENT '用户ID',
  `data_source` VARCHAR(50) NOT NULL DEFAULT 'xiaomi_sport' COMMENT '数据来源：xiaomi_sport=小米运动健康',
  `source_id` VARCHAR(100) COMMENT '来源数据ID',
  `data_hash` VARCHAR(64) NOT NULL COMMENT '数据哈希值（用于防重）',
  `measure_date` DATE NOT NULL COMMENT '测量日期',
  `measure_time` TIMESTAMP NOT NULL COMMENT '测量时间',
  `weight` DECIMAL(5, 2) NOT NULL COMMENT '体重（kg）',
  `bmi` DECIMAL(5, 2) COMMENT 'BMI指数',
  `body_fat` DECIMAL(5, 2) COMMENT '体脂率（%）',
  `muscle_mass` DECIMAL(5, 2) COMMENT '肌肉量（kg）',
  `bone_mass` DECIMAL(5, 2) COMMENT '骨量（kg）',
  `water` DECIMAL(5, 2) COMMENT '水分（%）',
  `protein` DECIMAL(5, 2) COMMENT '蛋白质（%）',
  `bmr` INT COMMENT '基础代谢率',
  `visceral_fat` DECIMAL(5, 2) COMMENT '内脏脂肪等级',
  `body_age` INT COMMENT '身体年龄',
  `body_score` INT COMMENT '身体评分',
  -- 八电极秤详细数据
  `body_shape` INT COMMENT '体型',
  `fat_mass` DECIMAL(5, 2) COMMENT '脂肪量（kg）',
  `left_lower_limb_fat_mass` DECIMAL(5, 2) COMMENT '左下肢脂肪量',
  `left_lower_limb_fat_rank` INT COMMENT '左下肢脂肪等级',
  `left_lower_limb_muscle_mass` INT COMMENT '左下肢肌肉量',
  `left_lower_limb_muscle_rank` INT COMMENT '左下肢肌肉等级',
  `left_upper_limb_fat_mass` DECIMAL(5, 2) COMMENT '左上肢脂肪量',
  `left_upper_limb_fat_rank` INT COMMENT '左上肢脂肪等级',
  `left_upper_limb_muscle_mass` DECIMAL(5, 2) COMMENT '左上肢肌肉量',
  `left_upper_limb_muscle_rank` INT COMMENT '左上肢肌肉等级',
  `limbs_fat_balance` INT COMMENT '四肢脂肪平衡',
  `limbs_muscle_balance` INT COMMENT '四肢肌肉平衡',
  `limbs_skeletal_muscle_index` DECIMAL(5, 2) COMMENT '四肢骨骼肌指数',
  `lower_limb_fat_balance` INT COMMENT '下肢脂肪平衡',
  `lower_limb_muscle_balance` INT COMMENT '下肢肌肉平衡',
  `recommended_calories_intake` INT COMMENT '推荐卡路里摄入',
  `right_lower_limb_fat_mass` DECIMAL(5, 2) COMMENT '右下肢脂肪量',
  `right_lower_limb_fat_rank` INT COMMENT '右下肢脂肪等级',
  `right_lower_limb_muscle_mass` DECIMAL(5, 2) COMMENT '右下肢肌肉量',
  `right_lower_limb_muscle_rank` INT COMMENT '右下肢肌肉等级',
  `right_upper_limb_fat_mass` DECIMAL(5, 2) COMMENT '右上肢脂肪量',
  `right_upper_limb_fat_rank` INT COMMENT '右上肢脂肪等级',
  `right_upper_limb_muscle_mass` DECIMAL(5, 2) COMMENT '右上肢肌肉量',
  `right_upper_limb_muscle_rank` INT COMMENT '右上肢肌肉等级',
  `trunk_fat_mass` DECIMAL(5, 2) COMMENT '躯干脂肪量',
  `trunk_fat_rank` INT COMMENT '躯干脂肪等级',
  `trunk_muscle_mass` DECIMAL(5, 2) COMMENT '躯干肌肉量',
  `trunk_muscle_rank` INT COMMENT '躯干肌肉等级',
  `upper_limb_fat_balance` INT COMMENT '上肢脂肪平衡',
  `upper_limb_muscle_balance` INT COMMENT '上肢肌肉平衡',
  `note` VARCHAR(500) COMMENT '备注',
  `raw_data` JSON COMMENT '原始数据（JSON格式）',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_data_hash` (`data_hash`) COMMENT '数据哈希唯一',
  INDEX `idx_user_date` (`user_id`, `measure_date`),
  INDEX `idx_user_source` (`user_id`, `data_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部数据-体重记录';

-- 外部数据 - 运动步数表
CREATE TABLE IF NOT EXISTS `external_step_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `user_id` INT NOT NULL COMMENT '用户ID',
  `data_source` VARCHAR(50) NOT NULL DEFAULT 'xiaomi_sport' COMMENT '数据来源：xiaomi_sport=小米运动健康',
  `source_id` VARCHAR(100) COMMENT '来源数据ID',
  `data_hash` VARCHAR(64) NOT NULL COMMENT '数据哈希值（用于防重）',
  `step_date` DATE NOT NULL COMMENT '步数日期',
  `steps` INT NOT NULL COMMENT '步数',
  `distance` DECIMAL(10, 2) COMMENT '距离（米）',
  `calories` INT COMMENT '消耗卡路里',
  `active_time` INT COMMENT '活跃时长（分钟）',
  `raw_data` JSON COMMENT '原始数据（JSON格式）',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_data_hash` (`data_hash`) COMMENT '数据哈希唯一',
  INDEX `idx_user_date` (`user_id`, `step_date`),
  INDEX `idx_user_source` (`user_id`, `data_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部数据-运动步数';
